# Generated by Django 3.2.5 on 2021-09-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210714_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='migration_user',
            name='district',
            field=models.IntegerField(db_column='DISTRICT_CD', default=0),
        ),
        migrations.AddField(
            model_name='migration_user',
            name='police_station',
            field=models.IntegerField(db_column='POLICE_STATION_CD', default=0),
        ),
        migrations.AddField(
            model_name='migration_user',
            name='state',
            field=models.IntegerField(db_column='STATE_CD', default=0),
        ),
    ]
